### ISSUE TITLE
T1055 Issue

### ISSUE THREAD

**Issue by xsuperbug** [redcanaryco/atomic-red-team#368] opened 2018-10-03 13:31 UTC
I have a problem with this technique. I tested DLL(Win32/x64) files using Mavinject command but ain't working right. I used notepad.exe for ProcessID and also, disabled my anti-virus solution. Got any suggestions?

**Comment by caseysmithrc** [comment] 2018-10-03 13:47
What command are you using?  What is the source code for the DLL you are trying to inject?
Any additional details you can provide will help us understand where the test is failing.

**Comment by caseysmithrc** [comment] 2018-10-04 13:31
Try using the full path to the DLL like this:
mavinject $pid /INJECTRUNNING C:\AtomicRedTeam\atomic-red-team-master\atomics\t1055\src\x64\T1055.dll

I'm pretty sure mavinejct wants the full path.  If that works I'll update the test.

Thanks

**Comment by caseysmithrc** [comment] 2018-10-04 13:33
Also, not sure why its not there, but I need to add the source code for that DLL to the repo.

**Comment by xsuperbug** [comment] 2018-10-05 12:17
I tried this way, but it didn't. What Windows operating system do you use?

Tested on:
Windows 10 x64
Version: 10.0.17134 Build 17134

Thanks.

**Comment by caseysmithrc** [comment] 2018-10-05 12:45
Yeah, it works for me on Windows 10 1803. 

That dll is designed to be injected into the PowerShell process, not another process.

It is specifically a dll that hooks SSL/TLS encrypted calls and displays the results.

Try using $pid to inject into current PowerShell process and also make sure you are using the correct build DLL, x64, x86 etc..

I'm going to close this issue since we have confirmed it working on multiple systems.

And it appears to be an isolated issue.

**Comment by xsuperbug** [comment] 2018-10-05 13:13
but Another technique-T1179 you mentioned. Am I wrong? The following technique works well.

Hook PowerShell TLS Encrypt/Decrypt Messages :
https://github.com/redcanaryco/atomic-red-team/blob/643472f5ee025427b5ec6b76ee45147f93b51920/atomics/T1179/T1179.md

**Comment by caseysmithrc** [comment] 2018-10-05 13:16
Yeah, let me see if we can rewrite this test to actually perform Proper Process Injection.

**Comment by caseysmithrc** [comment] 2018-11-10 23:58
Ok sir. I had some time to re-write this.  
I went ahead and crafted 5 tests.
     1. ProcessInject
    2. ApcInjectionAnyProcess
    3. ApcInjectionNewProcess
    4. IatInjection 
    5. ThreadHijack
Please give it a test and lets see how it works for you.  if so.  Lets ship it ! :-)
Thanks for the feedback, sorry it took me a bit to get this one done, but I think we have some solid tests now.

**Closed** 2019-01-16 14:43 UTC
